# Common proxy headers (for https)
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# We need to resolve in port 443
# WP Site 1 Server
server {
    listen 443 ssl;
    resolver 127.0.0.11 valid=10s ipv6=off; # Default resolver of Docker
    server_name site1.tdc.vv;

    ssl_certificate     /etc/nginx/certs/fullchain_wildcard.tdc.vv.pem;
    ssl_certificate_key /etc/nginx/certs/privkey_wildcard.tdc.vv.pem;

    location / {
        set $site1_server "wordpress-site1:80";
        proxy_pass http://$site1_server;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header Accept-Encoding gzip;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # Ignore error when service haven't started yet
        # proxy_connect_timeout 2s;
        # proxy_read_timeout 30s;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffering off;

        proxy_intercept_errors on;
        error_page 502 503 504 = @site1_down;
    }
    location @site1_down {
        return 502 "site1-server is not available\n";
    }
}

# WP Site 2 Server
server {
    listen 443 ssl;
    resolver 127.0.0.11 valid=10s ipv6=off; # Default resolver of Docker
    server_name site2.tdc.vv;

    ssl_certificate     /etc/nginx/certs/fullchain_wildcard.tdc.vv.pem;
    ssl_certificate_key /etc/nginx/certs/privkey_wildcard.tdc.vv.pem;

    location / {
        set $site2_server "wordpress-site2:80";
        proxy_pass http://$site2_server;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header Accept-Encoding gzip;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        # Ignore error when service haven't started yet
        # proxy_connect_timeout 2s;
        # proxy_read_timeout 30s;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_buffering off;

        proxy_intercept_errors on;
        error_page 502 503 504 = @site2_down;
    }
    location @site2_down {
        return 502 "site2-server is not available\n";
    }
}
