#cloud-config

hostname: ubuntu-2404-dev

users:
  - name: root
    lock_passwd: false
    plain_text_passwd: root
    ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR38alEXZ0GUhNcHqb15WysfWQ1BjD1qbfsVTo+Fp2vyzm6O4kA80eFxklIlMLUAtL1bDVzkkPeyNearXnlCu8l412cfDoWixF0KivpImyN27fd4uPnkXSVNqYF13qavbnHVmV7s4nTZR/wVkgnHlt2NbtSGcQ4Pd4oDkrjZg/G22OknHgeP66z2fioefgausJ7R1WBBhtWBdzhZlU5gtxsdub+Tv3AbxfVYkA28uy/+Yfzsh3prEfSTIeO7q6d0N8PkNh2lSUrovG2oXrMquqXWFJJk8agbpo8/szaI/vzFs0qZq6pJ4Ux7ca0T8t5+cu9C5Tn3fIZInbEHit8o0/zzqAR6PLWjDxOxql7tjuJ5lfP2w3002cVCDV1VjsgzsbRmMWnXrP7PaETQHoZyt1NL5GoFCfrk4NkSHTpbOMplh3FwFSV2gAfw3ELab+vew4O6sT4Ki13EEbLQ1xrHP4yQjMAezHEkYkybKTfyUsbyIf84Dyzc4W8f9fLsJnuB1bn0M2DJRPAcXZTydrMVJat6scb5IgHwRzJtxbTTZQ70STcW+xOgoa/jENw9kwWSKFiPCpWjcNzNnqX2Ru6jt8xz03BbRh6Q1+PsVHABPQp50MH+r/SmLvNh6EzG9HikijreGsF6yaFNGUhQjJ/i2I5OS7/7Wg5KAxGYo07hlm4Q== laptop-asus-Windows10

  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR38alEXZ0GUhNcHqb15WysfWQ1BjD1qbfsVTo+Fp2vyzm6O4kA80eFxklIlMLUAtL1bDVzkkPeyNearXnlCu8l412cfDoWixF0KivpImyN27fd4uPnkXSVNqYF13qavbnHVmV7s4nTZR/wVkgnHlt2NbtSGcQ4Pd4oDkrjZg/G22OknHgeP66z2fioefgausJ7R1WBBhtWBdzhZlU5gtxsdub+Tv3AbxfVYkA28uy/+Yfzsh3prEfSTIeO7q6d0N8PkNh2lSUrovG2oXrMquqXWFJJk8agbpo8/szaI/vzFs0qZq6pJ4Ux7ca0T8t5+cu9C5Tn3fIZInbEHit8o0/zzqAR6PLWjDxOxql7tjuJ5lfP2w3002cVCDV1VjsgzsbRmMWnXrP7PaETQHoZyt1NL5GoFCfrk4NkSHTpbOMplh3FwFSV2gAfw3ELab+vew4O6sT4Ki13EEbLQ1xrHP4yQjMAezHEkYkybKTfyUsbyIf84Dyzc4W8f9fLsJnuB1bn0M2DJRPAcXZTydrMVJat6scb5IgHwRzJtxbTTZQ70STcW+xOgoa/jENw9kwWSKFiPCpWjcNzNnqX2Ru6jt8xz03BbRh6Q1+PsVHABPQp50MH+r/SmLvNh6EzG9HikijreGsF6yaFNGUhQjJ/i2I5OS7/7Wg5KAxGYo07hlm4Q== laptop-asus-Windows10

  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR38alEXZ0GUhNcHqb15WysfWQ1BjD1qbfsVTo+Fp2vyzm6O4kA80eFxklIlMLUAtL1bDVzkkPeyNearXnlCu8l412cfDoWixF0KivpImyN27fd4uPnkXSVNqYF13qavbnHVmV7s4nTZR/wVkgnHlt2NbtSGcQ4Pd4oDkrjZg/G22OknHgeP66z2fioefgausJ7R1WBBhtWBdzhZlU5gtxsdub+Tv3AbxfVYkA28uy/+Yfzsh3prEfSTIeO7q6d0N8PkNh2lSUrovG2oXrMquqXWFJJk8agbpo8/szaI/vzFs0qZq6pJ4Ux7ca0T8t5+cu9C5Tn3fIZInbEHit8o0/zzqAR6PLWjDxOxql7tjuJ5lfP2w3002cVCDV1VjsgzsbRmMWnXrP7PaETQHoZyt1NL5GoFCfrk4NkSHTpbOMplh3FwFSV2gAfw3ELab+vew4O6sT4Ki13EEbLQ1xrHP4yQjMAezHEkYkybKTfyUsbyIf84Dyzc4W8f9fLsJnuB1bn0M2DJRPAcXZTydrMVJat6scb5IgHwRzJtxbTTZQ70STcW+xOgoa/jENw9kwWSKFiPCpWjcNzNnqX2Ru6jt8xz03BbRh6Q1+PsVHABPQp50MH+r/SmLvNh6EzG9HikijreGsF6yaFNGUhQjJ/i2I5OS7/7Wg5KAxGYo07hlm4Q== laptop-asus-Windows10

  

ssh_pwauth: true
disable_root: false

package_update: true
packages:
  - docker.io
  - git
  - maven
  - gradle
  - ansible
  - openjdk-21-jdk

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - bash /root/script.sh