#cloud-config

hostname: ${vm_name}

users:
  - name: root
    lock_passwd: false
    plain_text_passwd: root
    ssh_authorized_keys:
  %{ for key in ssh_keys ~}
- ${key}
  %{ endfor }

ssh_pwauth: true
disable_root: false

package_update: true
packages:
  - docker.io
  - git
  - maven
  - gradle
  - ansible
  - openjdk-21-jdk

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - bash /root/script.sh