services:
  nginx-https:
    image: nginx:alpine
    container_name: nginx-reverse-proxy-https
    restart: always
    ports:
      - "9100:443"
    volumes:
      - ./nginx/https-conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - common-network

networks:
  common-network:
    external: true