services:
  code-server:
    image: yeasy/simple-web:latest
    container_name: code-server
    restart: always
    ports:
      - "9001:80"
    networks:
      - common-network

  music-server:
    image: yeasy/simple-web:latest
    container_name: music-server
    restart: always
    ports:
      - "9002:80"
    networks:
      - common-network

  file-server:
    image: nginxdemos/hello:0.4
    container_name: file-server
    restart: always
    ports:
      - "9003:80"
    networks:
      - common-network

  video-server:
    image: nginxdemos/hello:0.4
    container_name: video-server
    restart: always
    ports:
      - "9004:80"
    networks:
      - common-network

networks:
  common-network:
    external: true