version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: "0:0"  # chạy root để tránh lỗi permission trong Multipass
    ports:
      - "8080:80"
    volumes:
      - /root/test-123:/srv
      - ./data:/database
      - ./config:/config
    command: >
      sh -c "
        filebrowser config init &&
        filebrowser users add admin admin --perm.admin || true &&
        filebrowser -r /srv
      "
    restart: unless-stopped