services:
  photoprism:
    image: photoprism/photoprism:ubuntu
    container_name: photoprism
    restart: always
    depends_on:
      - mariadb
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "change_this_password"

      #PHOTOPRISM_SITE_URL: "http://photoprism.your-domain.local/"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000

      # Disable AI / ML features
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"
      PHOTOPRISM_DISABLE_FACES: "true"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "true"
      PHOTOPRISM_DISABLE_PLACES: "true"

      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism_pass"

    volumes:
      - ./photos/originals:/photoprism/originals
      - ./photos/import:/photoprism/import
      - ./storage:/photoprism/storage

  mariadb:
    image: mariadb:11
    container_name: photoprism-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root_pass"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "photoprism_pass"
    volumes:
      - ./database:/var/lib/mysql