
upstream code_server {
    server code-server:8443;
}

server {
    listen 9000 ssl;
    server_name code.tdc.vv;

    ssl_certificate /etc/letsencrypt/live/code.your-domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/code.your-domain.com/privkey.pem;

    location / {
        proxy_pass http://code-server:8443;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
