services:
  rabbitmq3:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "56723:5672"
      - "35672:15672"
    env_file:
      - .env
    volumes:
      - rabbitmq_data3:/var/lib/rabbitmq

volumes:
  rabbitmq_data3:
